### ISSUE TITLE
Support for Cobertura XML?

### ISSUE THREAD

**Issue by yoe** [pjcj/Devel--Cover#286]
Hi,

I host some perl code inside a [gitlab instance](https://salsa.debian.org/debconf-video-team/sreview). Gitlab has support for parsing code coverage reports, which it can then use to visualize when a merge request changes the coverage on a particular line of code.

In order to be able to import the relevant coverage report, the report needs to be in the Cobertura XML format.

The details on the gitlab side can be found [in the gitlab documentation](https://docs.gitlab.com/ee/ci/yaml/README.html#artifactsreports).

It would be awesome if Devel::Cover were to add support for this report format.

**Comment by dboehmer** [comment]
Has someone tried [`TAP::Harness::JUnit`](https://metacpan.org/pod/TAP::Harness::JUnit) or [`Test2::Harness::Renderer::JUnit`](https://metacpan.org/pod/Test2::Harness::Renderer::JUnit) for this purpse?

**Comment by dboehmer** [comment]
This is a `gitlab-ci.yml` that I have just added JUnit to:

```yaml
---
stages:
  - test

prove:
  stage: test
  tags:
    - docker
  image: perl:latest
  before_script:
    - cpanm --notest Devel::Cover TAP::Harness::JUnit
    - cpanm --notest --installdeps .
  script:
    # Devel::Cover options
    #  -ignore_re  ^t/  do not include test files into code coverage
    #  -silent     1    do not output coverage data during tests
    - JUNIT_OUTPUT_FILE='junit.xml' prove
        --exec 'perl -MDevel::Cover=-ignore_re,^t/,-silent,1 -Ilib/'
        --harness 'TAP::Harness::JUnit'
        --verbose
  after_script:
    - cover -summary
  artifacts:
    when: always
    reports:
      junit: junit.xml
```

It reports the number of tests but nothing about coverage, though:

![Screenshot_20210730_222217](https://user-images.githubusercontent.com/116007/127707800-d4b0b3bc-4664-4c96-937c-e3608343932a.png)
